platform :ios, '9.0'

target 'HHVDoctorSDK-demo' do
  use_frameworks!

  pod 'HHVDoctorSDK', :git => "git@code.hh-medic.com:hh_public/hhvDoctorSDK.ios.git"

  pod 'SnapKit'
  
  pod 'FileBrowser'
  
  pod 'CocoaLumberjack'

  pod 'SVProgressHUD'
end
